Algoritmo "Curriculo Luane Loureiro"



Var
 nome, local, tel, email, opcao: caracter



Inicio
nome <- "luane C. A. Loureiro"
local <- "Rio de Janeiro - Brasil"
tel <- "(21)994736215"
email <- "luachan@gmail.com"

 escreval("Nome: "+ nome)
 escreval(local)
 escreval("Tel: "+tel)
 escreval("E-Mail: "+email)
 escreval("")
 
repita
 escreval("1 - Objetivo profissional")
 escreval("2 - Formação Académica")
 escreval("3 - Experiencia profissional")
 escreval("4 - Cursos e Certificações")
 escreval("5 - Idiomas")
 escreval("6 - Sair")
 leia (opcao)
 
    escolha opcao
            caso "1"
            escreval ("----------------Sobre----------------")
            escreval ("Amante das artes, desing e tecnologia.")
            escreval ("Estudei na escola de belas artes da UFRJ ")
            escreval ("E Dsenho industrial na Universidade Estácio de Sá, com bolsa integral.")
            escreval ("Participei de projeto de iniciação cientifica da FAU, quando estudava na UFRJ.")
            escreval ("Atualmente tenho minha própria empresa com marca registrada no INPI")
            escreval ("trabalho como designer e sou responsavel pelas midias sociais da empresa.")
            escreval ("Minha empresa tem mais de 5,5 mil curtidas no face book e mais de 3 mil seguidores no instagran")
            escreval ("Como hobie tenho uma página sobre video games que se chama ''to com lag'' que tem mais de 24 mil curtidas no facebook.")
            escreval ("Gosto de video games e tenho uma pequena coleção de games retrô.")
            escreval ("Já fiz parte de uma comunidade de Gametesters, eu jogava e fazia alguns relatórios e pesquisas de opinão")
            escreval ("participei de muitos Closed Betas e ja estava sendo convidada para alguns Closed alfa.")
            escreval ("Hoje, depois de anos a frente da minha empresa, busco novos desafios na área de tecnologia e Games")
            escreval ("Ja fiz alguns cursos, mas sou autodidata e estudo por conta própia Também")
            escreval ("Estudo diáriamente linguagem de programação e algoritimos")
            

            
            caso "2"
            escreval ("---------------Educação---------------")
            escreval ("")
            escreval ("Desenho Industrial - UESa  - Incopleto(9°semestre)")
            escreval ("Visual Art, Web Design and Graphic Design")
            escreval ("")
            escreval ("Bacharelado, Artes (Pintura) - UFRJ - Incompleto(8º semestre)")
            escreval ("Artes plásticas, Pintura e Desenho")
            escreval ("")
            escreval ("Bacharelado, Dança - UFRJ - Incopleto(10°semestre)")
            escreval ("Dança Moderna e Contemporânea")
            escreval ("Coreografia e vídeo produção")
            escreval ("")
            
            caso "3"
            escreval ("---------Experiência Profissional---------")
            escreval ("Graphic Design")
            escreval ("2012 - Atual")
            escreval ("Fundadora da empresa com marca registrada Nerd Shop - loja de artigos geek.")
            escreval ("Criação da logo e design institucional.")
            escreval ("trabalho de Marketing e campanhas para midias sociais da marca.")
            escreval ("Desenvolvimento de produtos, embalagens, impressos e papelaria.")
            escreval ("")
            escreval ("Estagio e Pesquisa na àrea de Restauração de Papel")
            escreval ("2007 /2008 - FAU-UFRJ")
            escreval ("Restauração de projetos arquitetônicos históricos na cidade do Rio de Janeiro.")
            escreval ("Conservação e Restauração em papel vegetal.")
            escreval ("Catalogar, organizar e arquivar os projetos restaurados.")
            escreval ("")
            
            caso "4"
            escreval("--------Cursos e Certificações--------")
            escreval ("")
            escreval ("CALARTS - Introduction to Game Design")
            escreval ("Introdução aos conceitos básicos de jogos e uma")
            escreval ("exploração de como esses conceitos básicos afetam a ")
            escreval ("maneira como os jogadores interagem com nossos jogos.")
            escreval ("Duração: 6 horas")
            escreval ("")
            escreval ("CALARTS - Character Design for Video Games")
            escreval ("Conceitos e abordagens envolvidos na criação do design ")
            escreval ("de personagens de sucesso que podem ser aplicados a ")
            escreval ("videogames.")
            escreval ("Duração: 9 horas")
            escreval ("")
            escreval ("Domestika - Female Character Portraits in Procreate")
            escreval ("Tecnicas de Ilustração Digital Para criar retratos cheios de imaginação.")
            escreval ("Duração: 16 lições (3h)")
            escreval ("")
            escreval ("Google - Grasshopper Coding Fundamentals I: JavaScript Basics")
            escreval ("Coding fundamentals, like functions, variables, and much more.")
            escreval ("")
            escreval ("Google - Grasshopper Coding Fundamentals II: JavaScript Basics")
            escreval ("Advanced coding fundamentals. Learn string & array manipulation, variable scope, the ternary operator, functions, callbacks and recursion.")
            escreval ("")
            escreval ("Programa Start By Capgemini")
            escreval ("Introdução a Lógica de Programação")
            escreval ("Lógica de Programação e Algoritmos I - Portugol")
            escreval ("Lógica de Programação e Algoritmos II - Portugol e PHP básico")
            escreval ("Logica de programação e Algoritmos III - Java")
            escreval ("")





            caso "5"
            escreval ("---------------Idiomas---------------")
            escreval ("")
            escreval ("Português - Nativo")
            escreval ("inglês - Avançado")
            escreval ("Japonês - Básico")
            escreval ("")
             fimescolha
 ate opcao = "6"
 
 
 
 
 
 


Fimalgoritmo