Algoritmo "orientação objeto(""

tipo
cadastrocliente = registro
nome: caractere
rg:caractere
idade:inteiro
fimregistro

Var
cliente1: cadastrocliente

Inicio
escreval("digite seu nome")
leia(cliente1.nome)

escreval("digite seu RG")
leia(cliente1.rg)

escreval("digite sua Idade")
leia(cliente1.idade)

escreval ("Nome: ", cliente1.nome, " - RG: ", cliente1.rg, " - idade: ", cliente1.idade)


Fimalgoritmo