Algoritmo "trabalhando com tipos"

Var
  numero1, numero2, soma, subtracao, multiplicacao : inteiro
  Divisao : real
  sucesso : logico
Inicio
   escreval ("Escreva um número: ")
   leia(numero1)
   escreval ("Escreva outro número: ")
    leia(numero2)
Soma <- numero1 + numero2
escreval ("soma")
escreval (soma)
Subtracao <- numero1 - numero2
Escreval ("subitração")
escreval (subtracao)
Multiplicacao <- numero1 * numero2
Escreval ("multiplicação")
escreval (multiplicacao)
Divisao <- numero1 / numero2
Escreval ("divição")
escreval (divisao)
sucesso <- numero1 > 10
Escreval ("o numero 1 é maiotr que 10?")
escreval (sucesso)


Fimalgoritmo